/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "led.h"
#include "uart.h"
#include "timebase.h"
#include "osKernel.h"

// #if !defined(__SOFT_FP__) && defined(__ARM_FP)
//   #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
// #endif

#define QUANTA 	50U
typedef uint32_t TaskProfiler;

TaskProfiler task_0_profiler, task_1_profiler, task_2_profiler;

void task0(void) {
	while(1) {
		task_0_profiler++;
	}
}

void task1(void) {
	while(1) {
		task_1_profiler++;
	}
}

void task2(void) {
	while(1) {
		task_2_profiler++;
	}
}

int main(void) {

	/* Init OS*/
	osKernelAddThreads(&task0, &task1, &task2);
	osKernelLaunch(QUANTA);
//	while(1) {
//
//	}
}



// int main(void)
// {
// 	led_init();
// 	uart_tx_init();
// 	timebase_init();

// 	while(1) {
// 		led_on();
// 		delay(100);
// 		led_off();
// 		delay(100);
// //		printf("Hello World!\r\n");
// 	}
//     /* Loop forever */
// 	for(;;);
// }
